swagger: "2.0"

info:
  title: Swagger Template
  description: A Template API
  version: "0.1"

paths:
  /analyse_coordinates:
    get:
      operationId: app.core.analyse_coords
      summary: Endpoint to receive coordinates and return bivouac zone
      parameters:
      - in: query
        name: e
        type: string
        description: E coordinate
      - in: query
        name: n
        type: string
        description: N coordinate
      produces:
      - text/plain
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: array
              items:
                type: integer
       
  /analyse_location:
    get:
      operationId: app.core.analyze_location
      summary: Endpoint to receive location and return bivouac zone
      parameters:
      - in: query
        name: long
        type: string
        description: Longitude
      - in: query
        name: lat
        type: string
        description: Latitude
      produces:
      - text/plain
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: array
              items:
                type: integer
          